# Generated by Django 3.1.6 on 2021-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(max_length=120)),
                ('collegrank', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
