# Generated by Django 3.1.6 on 2021-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(max_length=120)),
                ('collegrank', models.CharField(max_length=100)),
                ('colleadd', models.CharField(max_length=100)),
                ('TotalBranch', models.IntegerField()),
                ('Hostel', models.CharField(max_length=20)),
                ('collegeReviews', models.TextField()),
            ],
        ),
    ]
